In [1]:
import numpy as np
import time
import matplotlib.pyplot as plt
from wrappers import ISP
import optuna
import rawpy
import cv2
import h5py
import scipy

c:\Users\jithu\Desktop\git_repos\Differentiable-CUDA-based-ISP\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
with h5py.File(r"C:\Users\jithu\Desktop\git_repos\Differentiable-CUDA-based-ISP\Sample_input\0001_GT_RAW_010.MAT",'r') as f:
    Input = np.array(f['x'])

In [4]:
Input = Input*1023



In [ ]:
cfg = ISP.Configuration()
cfg.width = Input.shape[1]
cfg.length = Input.shape[0]
cfg.white_level = 1023
cfg.orientation = 1
cfg.DPC =False
cfg.DPC_threshold = 30
cfg.BLC = False
cfg.BLC_Offset = [0,0,0,0]
cfg.LSC = False
cfg.LSC_gain = [1.0, 1.0, 1.0, 1.0]
cfg.LSC_Max_radius = 1.0
cfg.AWB = True
cfg.AWB_Value_Given = False
cfg.AWB_gain = [1.8530800342559814, 0.9290269613265991, 1.3925764560699463]
cfg.CCM = False
cfg.CCM_gain = [0.664062500000000	,-0.045898437500000	,-0.120117187500000	,-0.542968750000000,	1.438476562500000,	0.071289062500000,	-0.176757812500000,	0.405273437500000,	0.475585937500000]
cfg.GAMMA = True
cfg.GAMMA_VALUE = 2.4
cfg.Color_Space_Conversion = True
cfg.Brightness_value = 1.2
cfg.Brightness = True
cfg.Saturation = True
cfg.Saturation_value = 1.1
cfg.Red = False
cfg.Blue = False
cfg.Green = False
cfg.Red_value = 1.0
cfg.Green_value = 1.0
cfg.Blue_value = 1.0

In [6]:
R, G, B = ISP.ISP(Input.flatten(),cfg)
image = np.dstack((R, G, B))
image = np.astype(image, np.uint8)
image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
x =int(Input.shape[1]*0.25)
y=int(Input.shape[0]*0.25)
image = cv2.resize(image, (x,y))

image = cv2.flip(image, 1)
cv2.imshow("Image", image)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
t = np.array(t)
k= np.array([
    [243,243,242],
    [200,200,200],
    [160,160,160],
    [122,122,121],
    [85,85,85],
    [52,52,52],
    [56,61,150],
    [70,148,73],
    [175,54,60],
    [231,199,31],
    [187,86,149],
    [8,133,161],
    [214,126,44],
    [80,91,166],
    [193,90,99],
    [94,60,108],
    [157,188,64],
    [224,168,46],
    [115,82,68],
    [194,150,130],
    [98,122,157],
    [87,108,67],
    [133,128,177],
    [103,189,170]
    
])
k
l =np.linalg.matmul(np.transpose(t), t)
m =np.matmul(np.transpose(t), k)
n = np.linalg.inv(l) 
ccm = np.linalg.matmul(n,m )

In [89]:
image = np.dstack((R, G, B))
image = image.astype(np.uint8)

# OpenCV uses BGR
image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)

x = int(Input.shape[1] * 0.25)
y = int(Input.shape[0] * 0.25)

image = cv2.resize(image, (x, y))

values = []

def mouse_callback(event, x, y, flags, param):
    if event == cv2.EVENT_LBUTTONDOWN:
        b, g, r = image[y, x]

        print(f"Position: ({x}, {y})")
        print(f"RGB: ({r}, {g}, {b})")
        print("-" * 30)

        values.append((r, g, b))
    
        # Draw marker
        cv2.circle(image, (x, y), 3, (0, 0, 255), -1)
        cv2.imshow("Image", image)

cv2.namedWindow("Image")
cv2.setMouseCallback("Image", mouse_callback)

cv2.imshow("Image", image)

while True:
    key = cv2.waitKey(1) & 0xFF
    if key == 27:  # ESC
        break

cv2.destroyAllWindows()

Position: (591, 1026)
RGB: (25, 17, 15)
------------------------------
Position: (584, 887)
RGB: (80, 53, 49)
------------------------------
Position: (595, 736)
RGB: (32, 37, 49)
------------------------------
Position: (592, 595)
RGB: (25, 26, 19)
------------------------------
Position: (592, 447)
RGB: (47, 43, 60)
------------------------------
Position: (597, 306)
RGB: (48, 72, 76)
------------------------------
Position: (445, 1018)
RGB: (81, 39, 24)
------------------------------
Position: (448, 876)
RGB: (16, 20, 42)
------------------------------
Position: (455, 729)
RGB: (86, 36, 33)
------------------------------
Position: (450, 599)
RGB: (19, 12, 17)
------------------------------
Position: (459, 450)
RGB: (73, 76, 47)
------------------------------
Position: (454, 295)
RGB: (97, 60, 35)
------------------------------
Position: (305, 1019)
RGB: (8, 12, 28)
------------------------------
Position: (309, 889)
RGB: (24, 36, 28)
------------------------------
Position: (318, 73

In [90]:
np.array(values)

array([[ 25,  17,  15],
       [ 80,  53,  49],
       [ 32,  37,  49],
       [ 25,  26,  19],
       [ 47,  43,  60],
       [ 48,  72,  76],
       [ 81,  39,  24],
       [ 16,  20,  42],
       [ 86,  36,  33],
       [ 19,  12,  17],
       [ 73,  76,  47],
       [ 97,  60,  35],
       [  8,  12,  28],
       [ 24,  36,  28],
       [ 64,  19,  15],
       [135,  97,  54],
       [ 76,  35,  45],
       [ 21,  39,  57],
       [110, 103, 108],
       [ 81,  76,  81],
       [ 68,  64,  68],
       [ 33,  31,  34],
       [ 13,  13,  13],
       [  3,   4,   2]], dtype=uint8)

In [91]:
import numpy as np

# Your extracted array (Ordered: Grayscale -> CMY/RGB -> Misc -> Natural)
k = values

# 1. Reorder 'k' to match the standard Macbeth layout (Row 1 -> Row 4)
source_reordered = np.concatenate([k[18:24], k[12:18], k[6:12], k[0:6]])

# 2. Normalize linear sensor data to [0.0, 1.0]
# Because this is fresh from debayering, we skip the inverse sRGB gamma formula.
source_linear = source_reordered / 255.0

# 3. Standard Reference Linear sRGB values (D65)
reference_linear = np.array([
    [0.153, 0.086, 0.061], [0.443, 0.287, 0.226], [0.126, 0.198, 0.323], [0.095, 0.147, 0.061], 
    [0.224, 0.220, 0.419], [0.137, 0.498, 0.407], [0.640, 0.198, 0.040], [0.081, 0.106, 0.372], 
    [0.407, 0.095, 0.122], [0.107, 0.048, 0.153], [0.372, 0.488, 0.076], [0.686, 0.347, 0.040],
    [0.034, 0.054, 0.278], [0.126, 0.291, 0.081], [0.312, 0.035, 0.044], [0.781, 0.575, 0.036], 
    [0.380, 0.095, 0.291], [0.054, 0.247, 0.372], [0.905, 0.905, 0.865], [0.575, 0.581, 0.575], 
    [0.353, 0.353, 0.353], [0.191, 0.195, 0.191], [0.091, 0.091, 0.091], [0.031, 0.031, 0.031]
])

# 4. Compute the 3x3 CCM using Moore-Penrose pseudo-inverse (Least Squares)
ccm, residuals, rank, s = np.linalg.lstsq(source_linear, reference_linear, rcond=None)

# 5. Column-normalize to preserve White Balance
# This ensures that neutral grays (R=G=B) stay perfectly neutral after matrix multiplication.
ccm_normalized = ccm / np.sum(ccm, axis=0)

print("Your Calculated 3x3 Color Correction Matrix (CCM):\n")
print(np.array2string(ccm_normalized, formatter={'float_kind': lambda x: f"{x: .4f}"}))

Your Calculated 3x3 Color Correction Matrix (CCM):

[[ 0.9711  1.0577  0.4445]
 [-2.2069 -2.3628  0.8061]
 [ 2.2358  2.3051 -0.2506]]


In [92]:
reference_linear =reference_linear* 255.0

In [93]:
reference_linear 

array([[ 39.015,  21.93 ,  15.555],
       [112.965,  73.185,  57.63 ],
       [ 32.13 ,  50.49 ,  82.365],
       [ 24.225,  37.485,  15.555],
       [ 57.12 ,  56.1  , 106.845],
       [ 34.935, 126.99 , 103.785],
       [163.2  ,  50.49 ,  10.2  ],
       [ 20.655,  27.03 ,  94.86 ],
       [103.785,  24.225,  31.11 ],
       [ 27.285,  12.24 ,  39.015],
       [ 94.86 , 124.44 ,  19.38 ],
       [174.93 ,  88.485,  10.2  ],
       [  8.67 ,  13.77 ,  70.89 ],
       [ 32.13 ,  74.205,  20.655],
       [ 79.56 ,   8.925,  11.22 ],
       [199.155, 146.625,   9.18 ],
       [ 96.9  ,  24.225,  74.205],
       [ 13.77 ,  62.985,  94.86 ],
       [230.775, 230.775, 220.575],
       [146.625, 148.155, 146.625],
       [ 90.015,  90.015,  90.015],
       [ 48.705,  49.725,  48.705],
       [ 23.205,  23.205,  23.205],
       [  7.905,   7.905,   7.905]])

In [94]:
a1 =np.linalg.inv(np.matmul(np.transpose(values),values))
a2 = (np.matmul(np.transpose(values),reference_linear))
np.matmul(a1,a2)

array([[ 1857.7019177 ,  1960.48185917,  2081.78173004],
       [ 3417.47309321,  3724.47135557,  3850.69305866],
       [-6238.78974853, -7544.27977862, -8853.10055122]])

In [88]:
# 1. (X^T * X)^-1 
# We apply the inverse to the dot product of the transposed values and the values
a1 = np.linalg.inv(np.matmul(np.transpose(values), values))

# 2. (X^T * Y)
# The dot product of the transposed values and the reference targets
a2 = np.matmul(np.transpose(values), reference_linear)

# 3. Multiply them together
ccm = np.matmul(a1, a2)

print("Calculated CCM:\n", ccm)

Calculated CCM:
 [[10553.88269554  7071.02759621  4188.64517694]
 [   33.5912153     70.34932802   154.30836189]
 [-4615.9015121  -2950.37370683 -1675.55326478]]


In [83]:
# Assuming 'Input' is your original loaded image
# image = Input.copy() 
# image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)

# Resize for display
x_dim = int(image.shape[1] )
y_dim = int(image.shape[0] )
image = cv2.resize(image, (x_dim, y_dim))

# We need a clean copy to draw temporary rectangles over without ruining the base image
image_display = image.copy()

values = []
drawing = False
start_pt = (-1, -1)

def mouse_callback(event, x, y, flags, param):
    global drawing, start_pt, image_display, image
    
    # 1. Left click pressed: Start recording the area
    if event == cv2.EVENT_LBUTTONDOWN:
        drawing = True
        start_pt = (x, y)
        
    # 2. Mouse moving: Draw a temporary rectangle to guide the user
    elif event == cv2.EVENT_MOUSEMOVE:
        if drawing:
            # Refresh from the base image so we don't draw an infinite trail of boxes
            image_display = image.copy()
            cv2.rectangle(image_display, start_pt, (x, y), (0, 255, 0), 1)
            cv2.imshow("Image", image_display)
            
    # 3. Left click released: Finalize the area and calculate the average
    elif event == cv2.EVENT_LBUTTONUP:
        drawing = False
        end_pt = (x, y)
        
        # Ensure coordinates are ordered correctly (top-left to bottom-right)
        x1, x2 = min(start_pt, end_pt), max(start_pt, end_pt)
        y1, y2 = min(start_pt, end_pt), max(start_pt, end_pt)
        
        # Check if it was just a single click (no area dragged)
        if x1 == x2 or y1 == y2:
            # Fallback to single pixel logic
            b, g, r = image[y, x]
            print(f"Single Pixel Position: ({x}, {y})")
        else:
            # Slice the numpy array to extract the Region of Interest (ROI)
            roi = image[y1:y2, x1:x2]
            
            # Calculate the average (cv2.mean returns a 4-tuple, we slice the first 3 for B,G,R)
            avg_bgr = cv2.mean(roi)[:3]
            b, g, r = [int(v) for v in avg_bgr]
            
            print(f"Selected Area: Start({x1}, {y1}) to End({x2}, {y2})")

        print(f"Average RGB: ({r}, {g}, {b})")
        print("-" * 30)

        values.append((r, g, b))
        
        # Draw a permanent red rectangle on the base image to mark the spot
        cv2.rectangle(image, (start_pt, start_pt), (end_pt, end_pt), (0, 0, 255), 2)
        image_display = image.copy()
        cv2.imshow("Image", image_display)


cv2.namedWindow("Image")
cv2.setMouseCallback("Image", mouse_callback)

cv2.imshow("Image", image_display)

while True:
    key = cv2.waitKey(1) & 0xFF
    if key == 27:  # ESC to exit
        break

cv2.destroyAllWindows()

TypeError: slice indices must be integers or None or have an __index__ method

TypeError: slice indices must be integers or None or have an __index__ method

TypeError: slice indices must be integers or None or have an __index__ method